# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 602)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/stellaris.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableMods = QtWidgets.QTableWidget(self.centralwidget)
        self.tableMods.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableMods.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableMods.setAlternatingRowColors(True)
        self.tableMods.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableMods.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableMods.setCornerButtonEnabled(False)
        self.tableMods.setObjectName("tableMods")
        self.tableMods.setColumnCount(8)
        self.tableMods.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMods.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMods.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMods.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMods.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMods.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMods.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMods.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMods.setHorizontalHeaderItem(7, item)
        self.tableMods.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout.addWidget(self.tableMods, 1, 0, 1, 12)
        self.buttonCheckDate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCheckDate.sizePolicy().hasHeightForWidth())
        self.buttonCheckDate.setSizePolicy(sizePolicy)
        self.buttonCheckDate.setMinimumSize(QtCore.QSize(87, 28))
        self.buttonCheckDate.setMaximumSize(QtCore.QSize(87, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/recycle1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCheckDate.setIcon(icon1)
        self.buttonCheckDate.setIconSize(QtCore.QSize(20, 20))
        self.buttonCheckDate.setObjectName("buttonCheckDate")
        self.gridLayout.addWidget(self.buttonCheckDate, 0, 1, 1, 1)
        self.buttonLoadAll = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(87)
        sizePolicy.setVerticalStretch(28)
        sizePolicy.setHeightForWidth(self.buttonLoadAll.sizePolicy().hasHeightForWidth())
        self.buttonLoadAll.setSizePolicy(sizePolicy)
        self.buttonLoadAll.setMinimumSize(QtCore.QSize(87, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/downloads.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadAll.setIcon(icon2)
        self.buttonLoadAll.setIconSize(QtCore.QSize(20, 20))
        self.buttonLoadAll.setObjectName("buttonLoadAll")
        self.gridLayout.addWidget(self.buttonLoadAll, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStatusTip("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.buttonCancel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCancel.setEnabled(True)
        self.buttonCancel.setMinimumSize(QtCore.QSize(87, 28))
        self.buttonCancel.setMaximumSize(QtCore.QSize(87, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCancel.setIcon(icon3)
        self.buttonCancel.setIconSize(QtCore.QSize(20, 20))
        self.buttonCancel.setFlat(False)
        self.buttonCancel.setObjectName("buttonCancel")
        self.gridLayout.addWidget(self.buttonCancel, 0, 4, 1, 1)
        self.buttonCheck = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCheck.setMinimumSize(QtCore.QSize(43, 28))
        self.buttonCheck.setMaximumSize(QtCore.QSize(43, 28))
        self.buttonCheck.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.buttonCheck.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/checkall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCheck.setIcon(icon4)
        self.buttonCheck.setIconSize(QtCore.QSize(20, 20))
        self.buttonCheck.setCheckable(True)
        self.buttonCheck.setChecked(False)
        self.buttonCheck.setAutoRepeat(False)
        self.buttonCheck.setFlat(True)
        self.buttonCheck.setObjectName("buttonCheck")
        self.gridLayout.addWidget(self.buttonCheck, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 20))
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionID = QtWidgets.QAction(MainWindow)
        self.actionID.setObjectName("actionID")
        self.actionName = QtWidgets.QAction(MainWindow)
        self.actionName.setObjectName("actionName")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.main_win = QtWidgets.QAction(MainWindow)
        self.main_win.setCheckable(False)
        self.main_win.setAutoRepeat(False)
        self.main_win.setObjectName("main_win")
        self.actionCloseAll = QtWidgets.QAction(MainWindow)
        self.actionCloseAll.setObjectName("actionCloseAll")
        self.actionListOut = QtWidgets.QAction(MainWindow)
        self.actionListOut.setObjectName("actionListOut")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Update Stellaris Mod"))
        self.tableMods.setSortingEnabled(True)
        item = self.tableMods.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableMods.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item.setToolTip(_translate("MainWindow", "Название мода"))
        item = self.tableMods.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID"))
        item.setToolTip(_translate("MainWindow", "ID мода (по steam)"))
        item = self.tableMods.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Размер, кбайт"))
        item.setToolTip(_translate("MainWindow", "Размер установленного мода"))
        item = self.tableMods.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата"))
        item.setToolTip(_translate("MainWindow", "Дата установлоенного мода"))
        item = self.tableMods.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Статус"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Результат проверки</p><p><span style=\" color:#00ff00;\">OK </span><span style=\" color:#000000;\">- мод в норме</span></p><p><span style=\" color:#a6a600;\">OUT </span><span style=\" color:#000000;\">- есть новая версия</span></p><p><span style=\" color:#ff0000;\">ERROR</span><span style=\" color:#000000;\"> - ошибка</span></p><p><span style=\" color:#ffaa00;\">CANCEL</span><span style=\" color:#000000;\"> - отмена</span></p><p><span style=\" color:#000000;\">LOAD - мод скачен</span></p></body></html>"))
        item = self.tableMods.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Дата smods"))
        item.setToolTip(_translate("MainWindow", "Дата мода на сайте"))
        item = self.tableMods.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Размер smods"))
        item.setToolTip(_translate("MainWindow", "Размер мода на сайте"))
        self.buttonCheckDate.setStatusTip(_translate("MainWindow", "Проверить состояние модов"))
        self.buttonCheckDate.setText(_translate("MainWindow", "Проверить"))
        self.buttonLoadAll.setStatusTip(_translate("MainWindow", "Загрузить выбранные моды"))
        self.buttonLoadAll.setText(_translate("MainWindow", "Загрузить"))
        self.label.setText(_translate("MainWindow", "Установленные моды"))
        self.buttonCancel.setStatusTip(_translate("MainWindow", "Отмена операции"))
        self.buttonCancel.setText(_translate("MainWindow", "Отмена"))
        self.buttonCheck.setStatusTip(_translate("MainWindow", "Выбрать все"))
        self.actionID.setText(_translate("MainWindow", "Копировать ID"))
        self.actionName.setText(_translate("MainWindow", "Копировать Название"))
        self.actionAbout.setText(_translate("MainWindow", "О программе"))
        self.actionOptions.setText(_translate("MainWindow", "Настройки"))
        self.actionInfo.setText(_translate("MainWindow", "Показать инфо"))
        self.main_win.setText(_translate("MainWindow", "Главное окно"))
        self.actionCloseAll.setText(_translate("MainWindow", "Закрыть все окна"))
        self.actionListOut.setText(_translate("MainWindow", "Копировать список для обновления"))

