# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Options.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogOptions(object):
    def setupUi(self, DialogOptions):
        DialogOptions.setObjectName("DialogOptions")
        DialogOptions.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogOptions.resize(522, 399)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogOptions.sizePolicy().hasHeightForWidth())
        DialogOptions.setSizePolicy(sizePolicy)
        DialogOptions.setMinimumSize(QtCore.QSize(522, 399))
        DialogOptions.setMaximumSize(QtCore.QSize(522, 441))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/stellaris.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogOptions.setWindowIcon(icon)
        DialogOptions.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.textEdit = QtWidgets.QTextEdit(DialogOptions)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(DialogOptions)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 130, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(DialogOptions)
        self.label.setGeometry(QtCore.QRect(30, 15, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogOptions)
        self.label_2.setGeometry(QtCore.QRect(30, 89, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.toolButton = QtWidgets.QToolButton(DialogOptions)
        self.toolButton.setGeometry(QtCore.QRect(450, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("background-color: rgb(247, 246, 244);")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(DialogOptions)
        self.toolButton_2.setGeometry(QtCore.QRect(450, 90, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("background-color: rgb(247, 246, 244);")
        self.toolButton_2.setObjectName("toolButton_2")
        self.saveButton = QtWidgets.QPushButton(DialogOptions)
        self.saveButton.setGeometry(QtCore.QRect(20, 360, 101, 31))
        self.saveButton.setStyleSheet("background-color: rgb(247, 246, 244);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setIconSize(QtCore.QSize(20, 20))
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(DialogOptions)
        self.cancelButton.setGeometry(QtCore.QRect(130, 360, 101, 31))
        self.cancelButton.setStyleSheet("background-color: rgb(247, 246, 244);")
        self.cancelButton.setObjectName("cancelButton")
        self.label_3 = QtWidgets.QLabel(DialogOptions)
        self.label_3.setGeometry(QtCore.QRect(110, 170, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogOptions)
        self.label_4.setGeometry(QtCore.QRect(110, 200, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(DialogOptions)
        self.lineEdit.setGeometry(QtCore.QRect(360, 170, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(DialogOptions)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 200, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(DialogOptions)
        self.label_5.setGeometry(QtCore.QRect(140, 230, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(DialogOptions)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 230, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setMaxLength(2)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(DialogOptions)
        self.label_6.setGeometry(QtCore.QRect(80, 290, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(DialogOptions)
        self.label_7.setGeometry(QtCore.QRect(130, 250, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(DialogOptions)
        self.label_8.setGeometry(QtCore.QRect(140, 310, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(DialogOptions)
        self.lineEdit_4.setGeometry(QtCore.QRect(360, 260, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setMaxLength(2)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(DialogOptions)
        self.lineEdit_5.setGeometry(QtCore.QRect(360, 290, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setMaxLength(2)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(DialogOptions)
        self.lineEdit_6.setGeometry(QtCore.QRect(360, 320, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setMaxLength(2)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.retranslateUi(DialogOptions)
        QtCore.QMetaObject.connectSlotsByName(DialogOptions)

    def retranslateUi(self, DialogOptions):
        _translate = QtCore.QCoreApplication.translate
        DialogOptions.setWindowTitle(_translate("DialogOptions", "Настройки"))
        self.label.setToolTip(_translate("DialogOptions", "users/Documents/Paradox Interactive/Stellaris"))
        self.label.setText(_translate("DialogOptions", "Путь к модам Stellaris"))
        self.label_2.setText(_translate("DialogOptions", "Каталог для загрузки модов"))
        self.toolButton.setToolTip(_translate("DialogOptions", "Выбор папки"))
        self.toolButton.setText(_translate("DialogOptions", "..."))
        self.toolButton_2.setToolTip(_translate("DialogOptions", "Выбор папки"))
        self.toolButton_2.setText(_translate("DialogOptions", "..."))
        self.saveButton.setToolTip(_translate("DialogOptions", "Сохранить пути"))
        self.saveButton.setText(_translate("DialogOptions", "Сохранить"))
        self.cancelButton.setToolTip(_translate("DialogOptions", "Отмена изменений"))
        self.cancelButton.setText(_translate("DialogOptions", "Отмена"))
        self.label_3.setText(_translate("DialogOptions", "Минимальный размер файла для stream"))
        self.label_4.setText(_translate("DialogOptions", "Размер куска файла в stream"))
        self.lineEdit.setInputMask(_translate("DialogOptions", "9999999999"))
        self.lineEdit_2.setInputMask(_translate("DialogOptions", "999999999999999"))
        self.label_5.setText(_translate("DialogOptions", "Максимальное количество загрузок"))
        self.lineEdit_3.setInputMask(_translate("DialogOptions", "99"))
        self.label_6.setText(_translate("DialogOptions", "Максимальное количество потоков для окон"))
        self.label_7.setText(_translate("DialogOptions", "Максимальное количество потоков для проверки"))
        self.label_8.setText(_translate("DialogOptions", "Максимальное количество загрузок из окон с информацией"))
        self.lineEdit_4.setInputMask(_translate("DialogOptions", "99"))
        self.lineEdit_5.setInputMask(_translate("DialogOptions", "99"))
        self.lineEdit_6.setInputMask(_translate("DialogOptions", "99"))

